# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       mesa
Summary:    Mesa graphics libraries
Version:    7.11~git4056.g0edb40c
Release:    0
Group:      System/Libraries
License:    MIT
URL:        http://www.mesa3d.org/beta
Source0:    mesa-%{version}.tar.bz2
Source1:    mesa-rpmlintrc
Source100:  mesa.yaml
Patch0:     0001-Revert-i915-Emit-a-single-relocation-per-vbo.patch
BuildRequires:  pkgconfig(glproto)
BuildRequires:  pkgconfig(dri2proto) >= 1.1
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(xxf86vm)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xfixes)
BuildRequires:  pkgconfig(xdamage)
BuildRequires:  pkgconfig(xi)
BuildRequires:  pkgconfig(xmu)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(talloc)
BuildRequires:  pkgconfig(libudev) >= 160
BuildRequires:  pkgconfig autoconf automake
BuildRequires:  expat-devel >= 2.0
BuildRequires:  python
BuildRequires:  libxml2-python
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  makedepend
BuildRequires:  wayland-devel >= 0.1~git716.gaa7bbb2
BuildRequires:  wayland-client
BuildRequires:  wayland-server


%description
Mesa is an open-source implementation of the OpenGL specification  -
a system for rendering interactive 3D graphics.



%package dri-drivers-devel
Summary:    Mesa-based DRI development files
Group:      Development/Libraries

%description dri-drivers-devel
Mesa-based DRI driver development files.

%package dri-i965-driver
Summary:    Mesa-based DRI drivers
Group:      Graphics/Display and Graphics Adaptation
Provides:   mesa-dri-drivers = %{version}-%{release}

%description dri-i965-driver
Mesa-based i965 DRI driver.

%package dri-i915-driver
Summary:    Mesa-based DRI drivers
Group:      Graphics/Display and Graphics Adaptation
Provides:   mesa-dri-drivers = %{version}-%{release}

%description dri-i915-driver
Mesa-based i915 DRI driver.

%package dri-swrast-driver
Summary:    Mesa-based DRI drivers
Group:      Graphics/Display and Graphics Adaptation
Provides:   mesa-dri-drivers = %{version}-%{release}

%description dri-swrast-driver
Mesa-based swrast DRI driver.

%package libglapi
Summary:    Mesa shared gl api library
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libglapi
Mesa shared gl api library.

%package libGL
Summary:    Mesa libGL runtime libraries and DRI drivers
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGL = %{version}-%{release}

%description libGL
Mesa libGL runtime library.

%package libGLESv1
Summary:    Mesa libGLESv1 runtime libraries
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv1 = %{version}-%{release}

%description libGLESv1
Mesa libGLESv1 runtime library.

%package libGLESv2
Summary:    Mesa libGLESv2 runtime libraries
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv2 = %{version}-%{release}

%description libGLESv2
Mesa libGLESv2 runtime library.

%package libGLESv2-compat
Summary:    Mesa libGLESv2 runtime compatibility library
Group:      System/Libraries
Requires:   libGLESv2.so.2
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libGLESv2.so

%description libGLESv2-compat
Mesa libGLESv2 runtime compatibility library.

%package libgbm
Summary:    Mesa generic/graphics buffer manager
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libgbm
Mesa generic/graphics buffer manager.

%package libEGL
Summary:    Mesa libEGL runtime libraries and DRI drivers
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libEGL = %{version}-%{release}

%description libEGL
Mesa libEGL runtime library.

%package libEGL-compat
Summary:    Mesa libEGL runtime compatibility library
Group:      System/Libraries
Requires:   libEGL.so.1
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libEGL.so

%description libEGL-compat
Mesa libEGL runtime compatibility library.

%package libGLU
Summary:    Mesa libGLU runtime library
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libGLU
Mesa libGLU runtime libraries

%package libOSMesa
Summary:    Mesa offscreen rendering libraries
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libOSMesa
Mesa offscreen rendering libraries-

%package libgbm-devel
Summary:    Mesa libgbm development package
Group:      Development/Libraries
Requires:   mesa-libgbm = %{version}-%{release}
Provides:   libgbm-devel

%description libgbm-devel
Mesa libgbm development package.

%package libglapi-devel
Summary:    Mesa libglapi development package
Group:      System/Libraries
Requires:   mesa-libglapi = %{version}-%{release}
Provides:   libglapi-devel

%description libglapi-devel
Mesa libglapi development package.

%package libGL-devel
Summary:    Mesa libGL development package
Group:      Development/Libraries
Requires:   mesa-libGL = %{version}-%{release}
Requires:   libX11-devel
Provides:   libGL-devel

%description libGL-devel
Mesa libGL development packages

%package libGLESv1-devel
Summary:    Mesa libGLESv1 development package
Group:      Development/Libraries
Requires:   mesa-libGLESv1 = %{version}-%{release}
Provides:   libGLESv1-devel

%description libGLESv1-devel
Mesa libGLESv1 development packages

%package libGLESv2-devel
Summary:    Mesa libGLESv2 development package
Group:      Development/Libraries
Requires:   mesa-libGLESv2 = %{version}-%{release}
Provides:   libGLESv2-devel
Obsoletes:   mesa-libGLESv2-compat

%description libGLESv2-devel
Mesa libGLESv2 development packages

%package libEGL-devel
Summary:    Mesa libEGL development package
Group:      Development/Libraries
Requires:   mesa-libEGL = %{version}-%{release}
Provides:   libEGL-devel
Obsoletes:   mesa-libEGL-compat

%description libEGL-devel
Mesa libEGL development packages

%package libGLU-devel
Summary:    Mesa libGLU development package
Group:      Development/Libraries
Requires:   mesa-libGLU = %{version}-%{release}
Requires:   libGL-devel
Provides:   libGLU-devel

%description libGLU-devel
Mesa libGLU development packages

%package libOSMesa-devel
Summary:    Mesa offscreen rendering development package
Group:      Development/Libraries
Requires:   mesa-libOSMesa = %{version}-%{release}

%description libOSMesa-devel
Mesa offscreen rendering development packages

%package libwayland-egl
Summary:    Mesa wayland-egl runtime libraries
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
Provides:   libwayland-egl = %{version}-%{release}

%description libwayland-egl
Mesa libwayland-egl runtime library.

%package libwayland-egl-devel
Summary:    Mesa wayland-egl development libraries
Group:      Development/Libraries
Requires:   libwayland-egl = %{version}-%{release}
Provides:   libwayland-egl-devel

%description libwayland-egl-devel
Mesa libwayland-egl development library.


%prep
%setup -q -n mesa-%{version} -b1

# 0001-Revert-i915-Emit-a-single-relocation-per-vbo.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre

# build mesa-libOSMesa
%define osmesa_flags --with-driver=osmesa --with-gallium-drivers= --with-dri-drivers="" --disable-glu --disable-glw --disable-glut --disable-egl
%reconfigure %{osmesa_flags} --with-osmesa-bits=32
make %{?jobs:-j%jobs}
mv %{_lib} osmesa32
make clean
# just to be sure...
[ `find . -name \*.o | wc -l` -eq 0 ] || exit 1

# << build pre

%reconfigure --disable-static \
    --disable-glut \
    --disable-glw \
    --disable-gl-osmesa \
    --with-gallium-drivers= \
    --enable-gallium-llvm=no \
    --enable-egl \
    --enable-gles1 \
    --enable-gles2 \
    --with-state-trackers=glx,dri \
    --with-driver=dri \
    --with-egl-platforms=x11,drm,wayland \
    --enable-shared-glapi \
    --with-dri-drivers=i915,i965,swrast \
    --with-dri-driverdir=%{_libdir}/dri

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# and osmesa
mv osmesa*/libOS* $RPM_BUILD_ROOT%{_libdir}
# create and install osmesa.pc
pushd src/mesa
make osmesa.pc
cp -vf osmesa.pc $RPM_BUILD_ROOT%{_libdir}/pkgconfig/
popd

# strip out undesirable headers
pushd $RPM_BUILD_ROOT%{_includedir}/GL
rm [a-fh-np-wyz]*.h glf*.h glut*.h
popd

#remove egl_glx.so, which is broken
pushd $RPM_BUILD_ROOT%{_libdir}
rm -f egl/egl_glx.so
popd

# << install post



















%post libglapi -p /sbin/ldconfig

%postun libglapi -p /sbin/ldconfig


%post libGL -p /sbin/ldconfig

%postun libGL -p /sbin/ldconfig


%post libGLESv1 -p /sbin/ldconfig

%postun libGLESv1 -p /sbin/ldconfig


%post libGLESv2 -p /sbin/ldconfig

%postun libGLESv2 -p /sbin/ldconfig


%post libGLESv2-compat -p /sbin/ldconfig

%postun libGLESv2-compat -p /sbin/ldconfig


%post libgbm -p /sbin/ldconfig

%postun libgbm -p /sbin/ldconfig


%post libEGL -p /sbin/ldconfig

%postun libEGL -p /sbin/ldconfig


%post libEGL-compat -p /sbin/ldconfig

%postun libEGL-compat -p /sbin/ldconfig


%post libGLU -p /sbin/ldconfig

%postun libGLU -p /sbin/ldconfig


%post libOSMesa -p /sbin/ldconfig

%postun libOSMesa -p /sbin/ldconfig


























%post libwayland-egl -p /sbin/ldconfig

%postun libwayland-egl -p /sbin/ldconfig






%files dri-drivers-devel
%defattr(-,root,root,-)
# >> files dri-drivers-devel
%{_libdir}/pkgconfig/dri.pc
# << files dri-drivers-devel

%files dri-i965-driver
%defattr(-,root,root,-)
# >> files dri-i965-driver
%{_libdir}/dri/i965_dri.so
# << files dri-i965-driver

%files dri-i915-driver
%defattr(-,root,root,-)
# >> files dri-i915-driver
%{_libdir}/dri/i915_dri.so
# << files dri-i915-driver

%files dri-swrast-driver
%defattr(-,root,root,-)
# >> files dri-swrast-driver
%{_libdir}/dri/swrast_dri.so
# << files dri-swrast-driver

%files libglapi
%defattr(-,root,root,-)
# >> files libglapi
%{_libdir}/libglapi.so.0
%{_libdir}/libglapi.so.0.*
# << files libglapi

%files libGL
%defattr(-,root,root,-)
# >> files libGL
%{_libdir}/libGL.so.1
%{_libdir}/libGL.so.1.2
# << files libGL

%files libGLESv1
%defattr(-,root,root,-)
# >> files libGLESv1
%{_libdir}/libGLESv1_CM.so.1
%{_libdir}/libGLESv1_CM.so.1.1.0
# << files libGLESv1

%files libGLESv2
%defattr(-,root,root,-)
# >> files libGLESv2
%{_libdir}/libGLESv2.so.2
%{_libdir}/libGLESv2.so.2.0.0
# << files libGLESv2

%files libGLESv2-compat
%defattr(-,root,root,-)
# >> files libGLESv2-compat
%{_libdir}/libGLESv2.so
# << files libGLESv2-compat

%files libgbm
%defattr(-,root,root,-)
# >> files libgbm
%{_libdir}/libgbm.so.1
%{_libdir}/libgbm.so.1.0
# << files libgbm

%files libEGL
%defattr(-,root,root,-)
# >> files libEGL
%{_libdir}/libEGL.so.1
%{_libdir}/libEGL.so.1.0
# << files libEGL

%files libEGL-compat
%defattr(-,root,root,-)
# >> files libEGL-compat
%{_libdir}/libEGL.so
# << files libEGL-compat

%files libGLU
%defattr(-,root,root,-)
# >> files libGLU
%{_libdir}/libGLU.so.1
%{_libdir}/libGLU.so.1.3.*
# << files libGLU

%files libOSMesa
%defattr(-,root,root,-)
# >> files libOSMesa
%{_libdir}/libOSMesa32.so.7*
# << files libOSMesa

%files libgbm-devel
%defattr(-,root,root,-)
# >> files libgbm-devel
%{_includedir}/gbm.h
%{_libdir}/libgbm.so
%{_libdir}/pkgconfig/gbm.pc
# << files libgbm-devel

%files libglapi-devel
%defattr(-,root,root,-)
# >> files libglapi-devel
%{_libdir}/libglapi.so
# << files libglapi-devel

%files libGL-devel
%defattr(-,root,root,-)
# >> files libGL-devel
%{_includedir}/GL/gl.h
%{_includedir}/GL/gl_mangle.h
%{_includedir}/GL/glext.h
%{_includedir}/GL/glx.h
%{_includedir}/GL/glx_mangle.h
%{_includedir}/GL/glxext.h
%dir %{_includedir}/GL/internal
%{_includedir}/GL/internal/dri_interface.h
%{_libdir}/libGL.so
%{_libdir}/pkgconfig/gl.pc
# << files libGL-devel

%files libGLESv1-devel
%defattr(-,root,root,-)
# >> files libGLESv1-devel
%{_libdir}/libGLESv1_CM.so
%{_includedir}/GLES/egl.h
%{_includedir}/GLES/gl.h
%{_includedir}/GLES/glext.h
%{_includedir}/GLES/glplatform.h
%{_libdir}/pkgconfig/glesv1_cm.pc
# << files libGLESv1-devel

%files libGLESv2-devel
%defattr(-,root,root,-)
# >> files libGLESv2-devel
%{_libdir}/libGLESv2.so
%{_includedir}/GLES2/gl2.h
%{_includedir}/GLES2/gl2ext.h
%{_includedir}/GLES2/gl2platform.h
%{_libdir}/pkgconfig/glesv2.pc
# << files libGLESv2-devel

%files libEGL-devel
%defattr(-,root,root,-)
# >> files libEGL-devel
%{_libdir}/libEGL.so
%dir %{_includedir}/EGL
%{_includedir}/EGL/egl.h
%{_includedir}/EGL/eglext.h
%{_includedir}/EGL/eglplatform.h
%dir %{_includedir}/KHR
%{_includedir}/KHR/khrplatform.h
%{_libdir}/pkgconfig/egl.pc
# << files libEGL-devel

%files libGLU-devel
%defattr(-,root,root,-)
# >> files libGLU-devel
%{_libdir}/libGLU.so
%{_libdir}/pkgconfig/glu.pc
%{_includedir}/GL/glu.h
%{_includedir}/GL/glu_mangle.h
# << files libGLU-devel

%files libOSMesa-devel
%defattr(-,root,root,-)
# >> files libOSMesa-devel
%{_includedir}/GL/osmesa.h
%{_libdir}/libOSMesa32.so
%{_libdir}/pkgconfig/osmesa.pc
# << files libOSMesa-devel

%files libwayland-egl
%defattr(-,root,root,-)
# >> files libwayland-egl
%{_libdir}/libwayland-egl.so.1
%{_libdir}/libwayland-egl.so.1.0
# << files libwayland-egl

%files libwayland-egl-devel
%defattr(-,root,root,-)
# >> files libwayland-egl-devel
%{_libdir}/libwayland-egl.so
%{_libdir}/pkgconfig/wayland-egl.pc
# << files libwayland-egl-devel

